### PR TITLE
Proc invocation style

### PR DESCRIPTION
**Pull request by NewAlexandria**
Dependency: PR #9 

This introduces the pass-as-argument style for block, [as mentioned in the community talk](https://github.com/bbatsov/ruby-style-guide/issues/419#issuecomment-85543119), and which is apparently part of Rubocop linting.

Sole commit on this PR:  a91d262

I'll rebase this PR, once *Chanel #9* is merged, in order to make a cleaner commit.

### CODE REVIEW

**Comment by ecampbell-mdsol** [comment]
+1 to this.

Once upon a time, using method `to_proc` incurred a performance penalty, and the "old time" Rubyists objected to using it for that reason.  But newer versions of Ruby have improved performance of `to_proc` significantly, and there is no reason not to use it whenever possible.

**Comment by pmavinkurve-mdsol** [comment]
@NewAlexandria the dependent PR has been merged!

**Comment by pmavinkurve-mdsol** [comment]
@umerkulovb since you have experience with Rubocop, would you like to take a stab at reviewing this PR, or better yet, to take it over, and get it merge ready? Thanks!
@cherbst-medidata fyi

**Comment by umerkulovb** [comment]
I'm OK with this PR. 
However, I have a bigger concern about this fork in general. For now, Balance team is using @houndci-bot to enforce `ruby`, `haml`, `js` styling which is obviously running rubocop over community-driven styles. We have also tuned them a little: https://github.com/mdsol/balance/blob/develop/.rubocop.yml

Since HoundCI used by Balance team is a commercial service, provided by Thoughtbot Inc, we can't enforce it to use Medidata's style guide. We can use our own hosted solution of hound, since it's opensource, but it is too much effort IMO. 

Summarizing all the above, I super appreciate your work supporting this fork, but at the meantime my opinion is that if we came up with a better styling solution, we should open a PR in a main repo. 

P.S. Shorter block chaining syntax proposed here, is being checked by my local rubocop setup already for a loooong time:

image

**Comment by pmavinkurve-mdsol** [comment]
@umerkulovb you have a valid point about the fork. 

I am looking over the master RSG and they now do support 2 indents! Looks like it was added in March 2014 in this PR https://github.com/bbatsov/ruby-style-guide/pull/298/ (https://github.com/bbatsov/ruby-style-guide#source-code-layout)

Perhaps some other groups/individuals did the legwork already of bringing it up more to a community standard that we may also desire. For the things we deviate on, we can open PRs to the master guide as you suggested. It may take time for us to adopt the master RSG fully but definitely looks promising. 

You convinced me :) I am happy to have Balance team take the lead on the path to this adoption. Are you already following the master RSG? I will get in touch with you in person next week or the week after.

**Comment by umerkulovb** [comment]
Yes we are! As I mentioned above we're using HoundCI, which is using rubocop v 0.37.0 (https://github.com/houndci/hound/blob/master/Gemfile#L34) released 9 days ago :)

**Comment by jcarres-mdsol** [comment]
FWIW, in japan we use Rubocop as it is, do not even have .rubocop.yml in the projects. Too much effort.

Rubocop has a nice flag "-a" which auto-corrects violations. We run that on our projects some times and that kind of makes them return back to the standard (if they ever derivated). For us is less effort this way.

I'd say ditching this repo in favor of the official style guide is a good idea.

**Comment by cherbst-medidata** [comment]
+1 for using the upstream guide, and I'd check out the -a flag too!

On Sat, Feb 13, 2016 at 4:24 AM, Jordi Polo Carres <notifications@github.com

**Comment by NewAlexandria** [comment]
bump

**Comment by pmavinkurve-mdsol** [comment]
I am in favor of closing this PR and us adopting the master guide. If there are objections please make a comment by end of this week. Thanks.

**Comment by umerkulovb** [comment]
Close + delete the fork :P

**Comment by jcarres-mdsol** [comment]
So, are we deleting the repo?

**Comment by pmavinkurve-mdsol** [comment]
@jcarres-mdsol - this is a fork not a repo, right? I would like us to deprecate it first - starting with closing this PR out. As for deletion - maybe we could do it after a while? I wouldn't expect the fork to count towards our private repo numbers, does it?

**Comment by pmavinkurve-mdsol** [comment]
Closing out this PR without merging as intended. There has been no objection in the past two weeks. Please let's use the master ruby-style-guide for Ruby guidelines. And if there are improvement/recommendations we can make a PR to the master repo.

Thanks all.

**Pull request closed without merging**
